use std::fmt::{self, Debug};
use std::collections::BTreeMap;

pub struct Quest {
    pub name: String,
    pub short_description: String,
    pub episode: Episode,
    pub monster_counts: BTreeMap<MonsterType, u32>
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Episode {
    I,
    II,
    IV
}

impl fmt::Display for Episode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Debug::fmt(self, f)
    }
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum MonsterType {
    Hildebear,
    Hildeblue,
    RagRappy,
    AlRappy,
    Monest,
    SavageWolf,
    BarbarousWolf,
    Booma,
    Gobooma,
    Gigobooma,
    Dragon,

    GrassAssassin,
    PoisonLily,
    NarLily,
    NanoDragon,
    EvilShark,
    PalShark,
    GuilShark,
    PofuillySlime,
    PouillySlime,
    PanArms,
    DeRolLe,

    Dubchic,
    Gilchic,
    Garanz,
    SinowBeat,
    SinowGold,
    Canadine,
    Canane,
    Dubwitch,
    VolOpt,

    Delsaber,
    ChaosSorcerer,
    DarkGunner,
    ChaosBringer,
    DarkBelra,
    Dimenian,
    LaDimenian,
    SoDimenian,
    Bulclaw,
    Claw,
    DarkFalz,

    Hildebear2,
    Hildeblue2,
    RagRappy2,
    AlRappy2,
    Monest2,
    PoisonLily2,
    NarLily2,
    GrassAssassin2,
    Dimenian2,
    LaDimenian2,
    SoDimenian2,
    DarkBelra2,
    BarbaRay,

    SavageWolf2,
    BarbarousWolf2,
    PanArms2,
    Dubchic2,
    Gilchic2,
    Garanz2,
    Dubwitch2,
    Delsaber2,
    ChaosSorcerer2,
    GolDragon,

    SinowBerill,
    SinowSpigell,
    Merillia,
    Meriltas,
    Mericarol,
    Merikle,
    Mericus,
    UlGibbon,
    ZolGibbon,
    Gibbles,
    Gee,
    GiGue,
    GalGryphon,

    Deldepth,
    Delbiter,
    Dolmolm,
    Dolmdarl,
    Morfos,
    Recobox,
    Epsilon,
    SinowZoa,
    SinowZele,
    IllGill,
    DelLily,
    OlgaFlow,

    SandRappy,
    DelRappy,
    Astark,
    SatelliteLizard,
    Yowie,
    MerissaA,
    MerissaAA,
    Girtablulu,
    Zu,
    Pazuzu,
    Boota,
    ZaBoota,
    BaBoota,
    Dorphon,
    DorphonEclair,
    Goran,
    PyroGoran,
    GoranDetonator,
    SaintMillion,
    Shambertin
}

impl fmt::Display for MonsterType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use self::MonsterType::*;

        let name = match *self {
            Hildebear => "Hildebear",
            Hildeblue => "Hildeblue",
            RagRappy => "Rag Rappy",
            AlRappy => "Al Rappy",
            Monest => "Monest",
            SavageWolf => "Savage Wolf",
            BarbarousWolf => "Barbarous Wolf",
            Booma => "Booma",
            Gobooma => "Gobooma",
            Gigobooma => "Gigobooma",
            Dragon => "Dragon",

            GrassAssassin => "Grass Assassin",
            PoisonLily => "Poison Lily",
            NarLily => "Nar Lily",
            NanoDragon => "Nano Dragon",
            EvilShark => "Evil Shark",
            PalShark => "Pal Shark",
            GuilShark => "Guil Shark",
            PofuillySlime => "Pofuilly Slime",
            PouillySlime => "Pouilly Slime",
            PanArms => "Pan Arms",
            DeRolLe => "De Rol Le",

            Dubchic => "Dubchic",
            Gilchic => "Gilchic",
            Garanz => "Garanz",
            SinowBeat => "Sinow Beat",
            SinowGold => "Sinow Gold",
            Canadine => "Canadine",
            Canane => "Canane",
            Dubwitch => "Dubwitch",
            VolOpt => "Vol Opt",

            Delsaber => "Delsaber",
            ChaosSorcerer => "Chaos Sorcerer",
            DarkGunner => "Dark Gunner",
            ChaosBringer => "Chaos Bringer",
            DarkBelra => "Dark Belra",
            Dimenian => "Dimenian",
            LaDimenian => "La Dimenian",
            SoDimenian => "So Dimenian",
            Bulclaw => "Bulclaw",
            Claw => "Claw",
            DarkFalz => "Dark Falz",

            Hildebear2 => "Hildebear (Ep. II)",
            Hildeblue2 => "Hildeblue (Ep. II)",
            RagRappy2 => "Rag Rappy (Ep. II)",
            AlRappy2 => "Al Rappy (Ep. II)",
            Monest2 => "Monest (Ep. II)",
            PoisonLily2 => "Poison Lily (Ep. II)",
            NarLily2 => "Nar Lily (Ep. II)",
            GrassAssassin2 => "Grass Assassin (Ep. II)",
            Dimenian2 => "Dimenian (Ep. II)",
            LaDimenian2 => "La Dimenian (Ep. II)",
            SoDimenian2 => "So Dimenian (Ep. II)",
            DarkBelra2 => "Dark Belra (Ep. II)",
            BarbaRay => "Barba Ray",

            SavageWolf2 => "Savage Wolf (Ep. II)",
            BarbarousWolf2 => "Barbarous Wolf (Ep. II)",
            PanArms2 => "Pan Arms (Ep. II)",
            Dubchic2 => "Dubchic (Ep. II)",
            Gilchic2 => "Gilchic (Ep. II)",
            Garanz2 => "Garanz (Ep. II)",
            Dubwitch2 => "Dubwitch (Ep. II)",
            Delsaber2 => "Delsaber (Ep. II)",
            ChaosSorcerer2 => "Chaos Sorcerer (Ep. II)",
            GolDragon => "Gol Dragon",

            SinowBerill => "Sinow Berill",
            SinowSpigell => "Sinow Spigell",
            Merillia => "Merillia",
            Meriltas => "Meriltas",
            Mericarol => "Mericarol",
            Merikle => "Merikle",
            Mericus => "Mericus",
            UlGibbon => "Ul Gibbon",
            ZolGibbon => "Zol Gibbon",
            Gibbles => "Gibbles",
            Gee => "Gee",
            GiGue => "Gi Gue",
            GalGryphon => "Gal Gryphon",

            Deldepth => "Deldepth",
            Delbiter => "Debiter",
            Dolmolm => "Dolmolm",
            Dolmdarl => "Dolmdarl",
            Morfos => "Morfos",
            Recobox => "Recobox",
            Epsilon => "Epsilon",
            SinowZoa => "Sinow Zoa",
            SinowZele => "Sinow Zele",
            IllGill => "Ill Gill",
            DelLily => "Del Lily",
            OlgaFlow => "Olga Flow",

            SandRappy => "Sand Rappy",
            DelRappy => "Del Rappy",
            Astark => "Astark",
            SatelliteLizard => "Satellite Lizard",
            Yowie => "Yowie",
            MerissaA => "Merissa A",
            MerissaAA => "Merissa AA",
            Girtablulu => "Girtablulu",
            Zu => "Zu",
            Pazuzu => "Pazuzu",
            Boota => "Boota",
            ZaBoota => "Za Boota",
            BaBoota => "Ba Boota",
            Dorphon => "Dorphon",
            DorphonEclair => "Dorphon Eclair",
            Goran => "Goran",
            PyroGoran => "Pyro Goran",
            GoranDetonator => "Goran Detonator",
            SaintMillion => "Saint Million",
            Shambertin => "Shambertin"
        };

        write!(f, "{}", name)
    }
}